# Generated by Django 5.2.8 on 2025-12-08 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_snippet_options_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='snippet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='MainApp.snippet', verbose_name='Сниппет'),
        ),
    ]
